#############################
### HYPRLAND MAIN CONFIG ###
#############################

# ==========================
# ENVIRONMENT
# ==========================
source = ~/.config/hypr/conf/env.conf


# ==========================
# MONITOR
# ==========================
source = ~/.config/hypr/conf/monitor.conf


# ==========================
# PROGRAMS
# ==========================
source = ~/.config/hypr/conf/programs.conf


# ==========================
# AUTOSTART
# ==========================
source = ~/.config/hypr/conf/autostart.conf


# ==========================
# LOOK & FEEL
# ==========================
source = ~/.config/hypr/conf/look.conf


# ==========================
# INPUT
# ==========================
source = ~/.config/hypr/conf/input.conf


# ==========================
# KEYBINDS
# ==========================
source = ~/.config/hypr/conf/keybinds.conf


# ==========================
# WINDOW RULES
# ==========================
source = ~/.config/hypr/conf/rules.conf
