#################
### AUTOSTART ###
#################

# ==========================
# UI / BAR / NOTIFICATION
# ==========================
exec-once = waybar
exec-once = mako


# ==========================
# NETWORK / BLUETOOTH
# ==========================
exec-once = nm-applet
exec-once = blueman-applet

# ==========================
# WALLPAPER
# ==========================
exec-once = ~/.local/bin/setwp --current

# ==========================
# IDLE / LOCK
# ==========================
exec-once = hypridle


# ==========================
# CLIPBOARD
# ==========================
exec-once = wl-paste --watch cliphist store


# ==========================
# UTILITIES
# ==========================
exec-once = wob

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = /usr/lib/xdg-desktop-portal-hyprland

# ==========================
# THEME / CURSOR / GTK
# ==========================

# ==========================
# THEME GLOBAL
# ==========================

# Cursor
env = XCURSOR_THEME, Bibata-Modern-Classic
env = XCURSOR_SIZE, 24

# Environment
exec-once = export GTK_THEME=Catppuccin-Blue-Dark
exec-once = export XDG_CURRENT_DESKTOP=Hyprland

# GTK settings
exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Catppuccin-Frappe'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Catppuccin-Blue-Dark'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# Audio
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland
exec-once = pipewire & pipewire-pulse & wireplumber
